import React,{useEffect,useRef,useState}from'react';
import{createRoot}from'react-dom/client';
import{ArrowRight,ArrowUpRight,Menu,X,Volume2,VolumeX}from'lucide-react';
import'./styles.css';

const work=[
['https://fluxweddings.ca/wp-content/uploads/2026/09/fluxweddings_vn_sneaks-65-683x1024.jpg','V + N','Edmonton / 2026'],
['https://fluxweddings.ca/wp-content/uploads/2026/09/ZC_sneaks_009-683x1024.jpg','Z + C','Alberta / 2026'],
['https://fluxweddings.ca/wp-content/uploads/2026/09/fluxweddings_vn_sneaks-92-683x1024.jpg','After dark','Editorial / 2026'],
['https://fluxweddings.ca/wp-content/uploads/2026/09/ANDREI-1-768x1152.jpg','The artist','Andrei Roman']
];
function Magnetic({children,href='#contact'}:{children:React.ReactNode,href?:string}){return <a className="magnetic" href={href}>{children}<ArrowUpRight size={15}/></a>}
function App(){const[menu,setMenu]=useState(false);const[sound,setSound]=useState(false);const cursor=useRef<HTMLDivElement>(null);useEffect(()=>{const move=(e:PointerEvent)=>{if(cursor.current)cursor.current.style.transform=`translate3d(${e.clientX}px,${e.clientY}px,0)`};window.addEventListener('pointermove',move);return()=>window.removeEventListener('pointermove',move)},[]);return <main>
<div ref={cursor} className="cursor"/><header><a className="wordmark" href="#top">FLUX®</a><div className="availability"><i/> 2027 commissions</div><nav><a href="#work">Index</a><a href="#method">Method</a><a href="#studio">Studio</a><Magnetic>Enquire</Magnetic></nav><button className="menu" onClick={()=>setMenu(!menu)}>{menu?<X/>:<Menu/>}</button></header>{menu&&<div className="menuSheet"><button onClick={()=>setMenu(false)}><X/></button>{['Work','Method','Studio','Enquire'].map((x,i)=><a key={x} onClick={()=>setMenu(false)} href={x==='Enquire'?'#contact':'#'+x.toLowerCase()}><small>0{i+1}</small>{x}</a>)}</div>}
<section id="top" className="opening"><div className="openingType"><p>Wedding photography / Alberta + wherever the story goes</p><h1><span>KEEP</span><span>THE</span><span>FEELING.</span></h1></div><div className="openingCard"><img src={work[0][0]} alt="Flux Weddings"/><span>01 — A living archive</span></div><div className="openingNote">Not content.<br/>Not poses.<br/><b>Evidence you were here.</b></div><a className="enter" href="#work">Enter archive <ArrowRight/></a></section>
<section id="work" className="index"><div className="indexIntro"><p>Selected / 2024—26</p><h2>An archive of<br/>people <i>fully alive.</i></h2><span>Drag your eyes. Keep scrolling.</span></div><div className="workRail">{work.slice(0,3).map((w,i)=><figure key={w[1]} className={'frame f'+(i+1)}><div className="photo"><img src={w[0]} alt={w[1]}/><span className="num">0{i+1}</span></div><figcaption><b>{w[1]}</b><span>{w[2]}</span></figcaption></figure>)}</div></section>
<section className="interlude"><p>WE DON'T MAKE<br/><span>PERFECT WEDDINGS.</span></p><p>WE MAKE<br/><em>REAL ONES ICONIC.</em></p></section>
<section id="method" className="method"><div className="methodSticky"><p>THE METHOD / 03 MOVES</p><h2>Calm direction.<br/>Sharp instinct.<br/><i>Zero theatre.</i></h2></div><div className="methodList"><article><span>01</span><div><h3>Read the room</h3><p>Before making photographs, understand the people. The energy. Who matters to whom. What is about to happen.</p></div></article><article><span>02</span><div><h3>Shape, don't stage</h3><p>Intervene when an image needs intention. Disappear when the moment already has everything it needs.</p></div></article><article><span>03</span><div><h3>Edit for memory</h3><p>Build a sequence with rhythm: loud, quiet, strange, beautiful. A wedding remembered as a story, not a folder.</p></div></article></div></section>
<section id="studio" className="studio"><div className="studioPhoto"><img src={work[3][0]} alt="Andrei Roman"/><button onClick={()=>setSound(!sound)} aria-label="Toggle sound">{sound?<Volume2/>:<VolumeX/>}<span>{sound?'Sound on':'Meet Andrei'}</span></button></div><div className="studioCopy"><p>THE PERSON / NOT THE BRAND</p><h2>Andrei<br/>Roman.</h2><p className="big">Photographer. Observer. Professional third wheel.</p><p className="small">The job is simple to describe and difficult to do well: make people comfortable enough to forget they're being photographed, then be ready when something real happens.</p><Magnetic href="#contact">Meet your photographer</Magnetic></div></section>
<section className="proof"><div className="proofTop"><p>WHAT YOU ACTUALLY GET</p><span>↓</span></div><div className="proofGrid"><article><strong>01</strong><h3>A point of view</h3><p>Not a preset applied to your wedding. A coherent visual language built around it.</p></article><article><strong>02</strong><h3>A calm presence</h3><p>Someone who knows when to lead, when to wait, and when to get out of the way.</p></article><article><strong>03</strong><h3>Something physical</h3><p>An archive deserves an object. The final story should exist somewhere other than a screen.</p></article><article className="proofCta"><p>Photography commissions</p><h3>Begin at<br/><b>$4,500</b></h3><Magnetic>Check your date</Magnetic></article></div></section>
<section className="quote"><p>Years from now,<br/>you won't care if it was <i>on trend.</i></p><h2>YOU'LL CARE<br/>IF IT TAKES<br/>YOU BACK.</h2></section>
<section id="contact" className="contact"><div className="contactTop"><p>YOUR TURN / 2027</p><span>Edmonton · Calgary · Destination</span></div><h2>Tell us<br/><i>everything.</i></h2><a className="giantLink" href="https://fluxweddings.ca/contact">Start a conversation <ArrowUpRight/></a><footer><a className="wordmark" href="#top">FLUX®</a><p>Wedding photography<br/>without the wedding-industry voice.</p><div><a href="https://www.instagram.com/fluxweddings/" target="_blank" rel="noreferrer">Instagram ↗</a><span>780.655.9116</span></div><small>© 2026 / Alberta, Canada</small></footer></section>
</main>}
createRoot(document.getElementById('root')!).render(<App/>);