import React from 'react';import{createRoot}from'react-dom/client';import{ArrowDown,ArrowUpRight,Menu}from'lucide-react';import'./styles.css';

const IMG={hero:'https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=2200&q=90',portrait:'https://images.unsplash.com/photo-1511285560929-80b456fea0bc?auto=format&fit=crop&w=1400&q=85',one:'https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1600&q=85',two:'https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1600&q=85',three:'https://images.unsplash.com/photo-1523438885200-e635ba2c371e?auto=format&fit=crop&w=1600&q=85',four:'https://images.unsplash.com/photo-1544078751-58fee2d8a03b?auto=format&fit=crop&w=1600&q=85'};
const Arrow=()=> <ArrowUpRight size={16} strokeWidth={1.4}/>;
function App(){return <main><section className="hero" style={{backgroundImage:`linear-gradient(180deg,rgba(12,12,10,.16),rgba(12,12,10,.48)),url(${IMG.hero})`}}><nav><a className="brand" href="#">FLUX <i>Weddings</i></a><div className="links"><a href="#work">Portfolio</a><a href="#story">About</a><a href="#experience">Experience</a><a className="inquire" href="#contact">Inquire <Arrow/></a></div><Menu className="menu"/></nav><div className="heroCopy"><p className="eyebrow light">Edmonton · Calgary · Worldwide</p><h1>Images that feel<br/><em>like you were there.</em></h1><p className="lead">Editorial refinement. Unscripted emotion.<br/>Wedding photography for celebrations with soul.</p></div><a className="scroll" href="#intro">Discover <ArrowDown size={14}/></a></section>
<section id="intro" className="intro"><p className="eyebrow">A study in presence</p><h2>Your wedding isn't<br/>a photoshoot. <em>It's a life event.</em></h2><div className="introText"><p>We create photographs that hold onto more than how your day looked — they preserve how it moved, sounded, and felt.</p><p>With an eye for honest moments and considered composition, Andrei documents your celebration without turning it into a production.</p></div></section>
<section id="work" className="gallery"><figure className="g1"><img src={IMG.one}/><figcaption><span>01</span> The celebration</figcaption></figure><figure className="g2"><img src={IMG.two}/><figcaption><span>02</span> The quiet moments</figcaption></figure><figure className="g3"><img src={IMG.three}/><figcaption><span>03</span> The details</figcaption></figure></section>
<section id="story" className="story"><div className="storyPhoto"><img src={IMG.portrait}/><span>Behind the lens</span></div><div className="storyCopy"><p className="eyebrow">Meet Andrei</p><h2>Direction when it<br/>elevates. <em>Space when<br/>the moment speaks.</em></h2><p>I believe the best wedding photographs happen when you forget about the camera. My role is to see what matters, guide with intention when needed, and leave room for everything real to unfold.</p><a className="textLink" href="#">The philosophy <Arrow/></a></div></section>
<section className="manifesto" style={{backgroundImage:`linear-gradient(rgba(15,14,12,.35),rgba(15,14,12,.5)),url(${IMG.four})`}}><p className="eyebrow light">For the deeply felt</p><blockquote>“The photographs you keep<br/>should feel <em>timeless</em> because<br/>the moments were real.”</blockquote></section>
<section id="experience" className="experience"><div><p className="eyebrow">The Flux experience</p><h2>Artfully documented.<br/><em>Effortlessly experienced.</em></h2></div><div className="steps"><article><span>01</span><h3>Intentional coverage</h3><p>Thoughtful direction and documentary instinct, balanced around the rhythm of your celebration.</p></article><article><span>02</span><h3>A tangible legacy</h3><p>Every couple receives an album. Your photographs deserve to live beyond a screen, handcrafted to be held for generations.</p></article><article><span>03</span><h3>Limited commissions</h3><p>A considered number of weddings each season means your story receives the attention and care it deserves.</p></article></div></section>
<section className="collections"><p className="eyebrow">Wedding commissions</p><h2>For celebrations<br/><em>worth remembering.</em></h2><p>Collections are tailored around the scale, pace, and priorities of your wedding. Photography collections begin at <strong>$4,500 CAD.</strong></p><a className="button" href="#contact">Explore the experience <Arrow/></a></section>
<section id="contact" className="contact"><p className="eyebrow light">Begin your story</p><h2>If these images feel like<br/><em>your kind of memories,</em><br/>we should talk.</h2><a href="mailto:hello@fluxweddings.ca">Tell us about your wedding <Arrow/></a><footer><div className="brand">FLUX <i>Weddings</i></div><p>Edmonton · Calgary · Banff · Worldwide</p><a href="https://www.instagram.com/fluxweddings/" target="_blank" rel="noreferrer" aria-label="Flux Weddings on Instagram">Instagram</a><small>© 2026 Flux Weddings</small></footer></section></main>}
createRoot(document.getElementById('root')!).render(<App/>);
